In [1]:
import numpy as np

In [41]:
b = np.arange(30).reshape((5,6))
B = np.tile(A = b, reps = (6,1,1))
print(B)
print(np.einsum('inj, ij -> nij', B, np.identity(6)))



[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]]
[[[ 0.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  2.  0.  0.  0.]
  [ 0.  0.  0.  3.  0.  0.]
  [ 0.  0.  0.  0.  4.  0.]
  [ 0.  0.  0.  0.  0.  5.]]

 [[ 6.  0.  0.  0.  0.  0.]
  [ 0.  7.  0.  0.  0.  0.]
  [ 0.  0.  8.  0.  0.  0.]
  [ 0.  0.  0.  9.  0.  0.]
  [ 0.  0.  0.  0. 10.  0.]
  [ 0.  0.  0.  0.

In [14]:
np.diag(a)

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [19]:
A = np.array([np.identity(2), np.identity(2)])
print(A.shape)
np.cov(A.reshape(4,2), rowvar=False)



(2, 2, 2)


array([[ 0.33333333, -0.33333333],
       [-0.33333333,  0.33333333]])

In [7]:
np.cov(A)

array([[ 0.5, -0.5],
       [-0.5,  0.5]])

In [43]:
L = [1,2,3][:3]
print(L)

[1, 2, 3]
